[tool.poetry]
name = "brain-games"
version = "0.1.0"
description = "Mind Games project"
authors = ["ТВОЙ_НИК <email@example.com>"]
packages = [
  { include = "brain_games" }
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
