name: hexlet-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies with UV
        run: |
          python3 -m pip install uv
          uv pip install --requirements requirements.txt

      - name: Run tests with UV
        run: |
          PYTHONPATH=. uv run pytest -vv
