name: hexlet-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем репозиторий
      - uses: actions/checkout@v4

      # Запускаем проверку Hexlet
      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ secrets.HEXLET_ID }}

