
name: hexlet-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: python3 -m pip install --user uv

      - run: |
          uv venv
          uv sync

      - run: |
          PYTHONPATH=$(pwd) uv run pytest -vv tests

