name: hexlet-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        run: python3 -m pip install --user uv

      - name: Create virtual environment and sync dependencies
        run: |
          uv venv --clear
          uv sync

